version: "3.9"

services:
  lac_sotu_dashboard_react:
    build: ./data-dashboard
    image: iisdevs/lac_sotu_dashboard_react:latest
    ports:
      - "3000:80"
    volumes:
      - ./data-dashboard/public:/usr/share/nginx/html
      - /app/node_modules

